"""initial migration

Revision ID: 3480d30fe906
Revises: 
Create Date: 2026-09-12 04:17:58.601885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3480d30fe906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.Enum('CO', 'US', name='pais_enum'), server_default='CO', nullable=False),
    sa.Column('moneda', sa.Enum('COP', 'USD', name='moneda_enum'), server_default='COP', nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moneda IN ('COP','USD')", name='ck_locales_moneda'),
    sa.CheckConstraint("pais IN ('CO','US')", name='ck_locales_pais'),
    sa.PrimaryKeyConstraint('id'),
    comment='Restaurantes de la cadena: Colombia y Florida'
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('pais', sa.Enum('CO', 'US', name='pais_enum'), server_default='CO', nullable=False),
    sa.Column('dias_entrega', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pais IN ('CO','US')", name='ck_proveedores_pais'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_proveedores_nombre'),
    comment='Proveedores de ingredientes (N:M con locales)'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('admin','operador','consulta')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_usuarios_email'),
    comment='Usuarios del backoffice para JWT'
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.Enum('kg', 'g', 'L', 'ml', 'unidad', name='unidad_enum'), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unidad IN ('kg','g','L','ml','unidad')", name='ck_ingredientes_unidad'),
    sa.CheckConstraint('costo_unitario >= 0', name='ck_ingredientes_costo_positivo'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_ingredientes_codigo'),
    comment='Catálogo de ingredientes con costos y umbral mínimo'
    )
    op.create_table('locales_proveedores',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('precio_acordado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('local_id', 'proveedor_id'),
    sa.UniqueConstraint('local_id', 'proveedor_id', name='uq_local_proveedor'),
    comment='Relación N:M locales-proveedores con condiciones comerciales'
    )
    op.create_table('inventario_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_minima', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_id', 'ingrediente_id', name='uq_inventario_local_ingrediente'),
    comment='Stock actual por local e ingrediente'
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_local_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'ajuste', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('entrada','salida','ajuste')", name='ck_movimientos_tipo'),
    sa.CheckConstraint('cantidad > 0', name='ck_movimientos_cantidad_positiva'),
    sa.ForeignKeyConstraint(['inventario_local_id'], ['inventario_local.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Kardex de movimientos: entradas, salidas y ajustes'
    )
    op.create_index('ix_movimientos_created_at', 'movimientos_inventario', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimientos_created_at', table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_table('inventario_local')
    op.drop_table('locales_proveedores')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('locales')
    # ### end Alembic commands ###
